### ISSUE TITLE
Handle 32bit CGO

### ISSUE THREAD

**Issue by Stebalien** [protocol/.github#131]
Unfortunately, 32bit tests will run without CGO support because the base-os is 64bit. We could either:

1. Run in a 32bit docker container (Ubuntu only).
2. Provide an option in config.json to disable 32bit tests.

For my current use-case (https://github.com/ipfs/go-bs-sqlite3/pull/3), simply disabling 32bit tests is likely the simplest option. We can support a 32bit environment on Linux, but I'm not sure how to go about it on Windows.

**Comment by mvdan** [comment]
When we added the GOARCH=386 step, I think we forgot that that also turns off CGO_ENABLED by default. Thanks for flagging this.

Ideally, `CGO_ENABLED=0 go test ./...` would succeed in every module - for example, `CGO_ENABLED=0 go test -short std` passes for me. It should be true for almost every library too, for the sake of making sure it doesn't require `CGO_ENABLED=1 GOARCH=$GOHOSTARCH` to build and run.

In practice I get that that's too high of a bar to set as a requirement. We have projects that straight up require CGo to work, especially the large ones like Lotus and go-ipfs. And if we use `CGO_ENABLED=1 GOARCH=386`, installing 32-bit libraries might be pretty complex - I think a similar downside applies to running a 32-bit Ubuntu container, unless I'm missing some simple+fast way to do that.

I think we could try keeping this on by default, and allowing to turn it off via an option like "cgo required". If too many repos end up needing that, then maybe this step could be opt-in rather than opt-out.

**Comment by Stebalien** [comment]
Hm. So yeah, we _should_ be disabling everything when CGO is disabled.  But once I fix that, we'll need to add some logic to skip go modules that don't _actually_ have any packages. Otherwise, `go test ./...` fails anyways.

**Comment by mvdan** [comment]
I think that "should be disabling everything when CGo is disabled" is a reasonable ask for libraries, especially those intended for consumption outside PL. But in our table of repos there will be a good portion of non-libraries, so I think overall it's not worth it to enforce `CGO_ENABLED=0 go test ./...` to succeed.

**Comment by Stebalien** [comment]
Ok, so this case was actually simpler. I just hid `Open` behind a cgo flag. That way, users can still import the library and reference the types, they just can't open the blockstore unless they have CGO enabled. That:

1. Fixes CI.
2. Should make this library easier to use when CGO may or may not be available.

**Comment by Stebalien** [comment]
https://github.com/ipfs/go-bs-sqlite3/pull/4

**Comment by marten-seemann** [comment]
Is there anything left to do on this issue, or can we kick the can down the road?

**Comment by mvdan** [comment]
I'd leave it open for a few months to see if any other repos reasonably require turning this off as we expand the list.

**Comment by Stebalien** [comment]
Eh... we have enough open issues. I'd rather just re-open if it becomes a problem.
