### ISSUE TITLE
Create GitHub releases in releaser/tag-pusher workflows

### ISSUE THREAD

**Issue by galargh** [protocol/.github#228]
The suggestion here is for the [versioning workflows](https://github.com/protocol/.github/blob/master/VERSIONING.md#using-the-versioning-workflows) and [manual version pushes](https://github.com/protocol/.github/blob/master/VERSIONING.md#dealing-with-manual-pushes) to create a GitHub release among with the version tag.

Below, I've gathered some ideas for the process from Slack discussions.

###### How to generate release notes?
- use [auto generated release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes); [API access to this feature](https://docs.github.com/en/rest/reference/repos#generate-release-notes-content-for-a-release)
- for versioning workflow - we could use the comments/description of the PR updating the version to create the release notes (Q: how to access PR in the workflow?)
- for manual push workflow - we could use the comments/description of the issue that was created as a result of pushing tag manually (Q: should we check if the release was created manually too?)

###### How to verify the GitHub release before subscribers get notified about it?
- initially create the GitHub release in a draft state (make it possible for owners to change this behaviour once they gain enough confidence in the workflow); [API access to this feature](https://docs.github.com/en/rest/reference/repos#create-a-release)

**Comment by marten-seemann** [comment]
> for manual push workflow - we could use the comments/description of the issue that was created as a result of pushing tag manually (Q: should we check if the release was created manually too?)

Ideally, this workflow is never executed. It only exists because GitHub doesn't allow us to restrict tag pushes (yet).

> initially create the GitHub release in a draft state (make it possible for owners to change this behaviour once they gain enough confidence in the workflow); API access to this feature

Can we do this, even though the git commit (and the tag) doesn't exist yet? 

> for versioning workflow - we could use the comments/description of the PR updating the version to create the release notes (Q: how to access PR in the workflow?)

There are multiple things we can do:
1. Use [artifacts](https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts) to store the text until the PR is merged, and then copy it from the artifact to the release notes. Problem: there might be multiple PRs suggesting the same release, and only one of them gets merged.
2. Is is possible to run a workflow when a PR is closed (and then check that it wasn't just closed, but actually merged), see https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359. Importantly, this does _not_ give us access to the merge commit, so this workflow might run before the `releaser` workflow has actually created the tag.

**Comment by marten-seemann** [comment]
Using the solution described in https://github.com/protocol/.github/issues/229#issuecomment-974815879 (and implemented in #230), we can get the PR number of the PR that created the release.
In principle, this should give us access to the comments posted on this PR _somehow_, but I'm not sure how tricky this will be in practice.

**Comment by lidel** [comment]
I've seen many of our GO packages  missing GitHub releases for tags created via `version.json` automation, making GitHub releases page stuck at release that is  1 or 2 year old.

Is anything blocking https://github.com/protocol/.github/pull/299?

**Comment by galargh** [comment]
Resolved by https://github.com/protocol/.github/pull/456.
