### ISSUE TITLE
copy-workflow fails if repo uses submodules 

### ISSUE THREAD

**Issue by galargh** [protocol/.github#248]
https://github.com/filecoin-project/go-commp-utils uses https://github.com/filecoin-project/filecoin-ffi as a submodule. The latter defines go1.13 in it's go.mod file. When we try to copy workflows for go-commp-utils, we also try to update go version in the submodule which fails: https://github.com/protocol/.github/runs/4485167112?check_suite_focus=true

We could temporarily fix it by adding filecoin-ffi to unified CI framework (which we should) but it won't stop the issue from reappearing during go upgrades for example.

**Comment by marten-seemann** [comment]
I think @mvdan had some thoughts about this, but I think that was somewhere on Slack and not on an issue here.

**Comment by mvdan** [comment]
The way many modules require filecoin-ffi today is quite broken; see https://github.com/filecoin-project/filecoin-ffi/issues/209. This is what leads to the git submodule and the replace directive, and the manual steps required to build the parent Go module.

I think we should focus on making filecoin-ffi easy to use as a Go module (see the link above), rather than adding ways to work around the problems it causes today :)

**Comment by galargh** [comment]
The initial issue - updating go.mod in submodules - has been resolved by updating only those go.mod files that are committed - https://github.com/pl-strflt/uci/commit/ddcf7dcefd146c42912454a11623d2084d7ea2d8.
