### ISSUE TITLE
release-check workflow fails when triggered from 3rd party repos

### ISSUE THREAD

**Issue by marten-seemann** [protocol/.github#254]
Example: https://github.com/libp2p/go-doh-resolver/runs/4548155702?check_suite_focus=true

It’s doing a git diff `${{ env.COMPARETO }}..${{ github.event.pull_request.head.sha }}`. The v0.3.1 tag exists in our as well as in the forked repo, the problem is probably the commit SHA.

@aschmahmann mentioned that we might need to do something like here: https://github.com/ipfs/go-ipfs/blob/master/.circleci/main.yml#L108-L124

**Comment by marten-seemann** [comment]
> The issue is that if a workflow is initiated by a pull from a fork, then the created GITHUB_TOKEN can have at most read privileges to everything. 

Is a `GITHUB_TOKEN` with `read` permissions not allowed to post on a PR? That would be surprising to me, after all, a contributor with the same permissions is allowed to comment on issues and PRs.

**Comment by galargh** [comment]
Yes, `GITHUB_TOKEN` gets only `read` permissions on pull requests: https://github.com/libp2p/go-doh-resolver/runs/4559777662?check_suite_focus=true#step:1:23 which makes the commenter action fail https://github.com/libp2p/go-doh-resolver/runs/4559777662?check_suite_focus=true#step:14:76 because of lacking permissions https://github.com/marocchino/sticky-pull-request-comment#error-resource-not-accessible-by-integration

I'm pretty sure what happens here is that the Pull Request permission cannot express ownership. So you're either granted access to writing to all PRs within a repo or none.

**Comment by galargh** [comment]
Release check, when run on forks, now outputs the release notes which can be copied manually. If this proves to be a common occurrence, we can set up an cron job that is going to post such release notes - closing for now.
