### ISSUE TITLE
run gofmt

### ISSUE THREAD

**Issue by marten-seemann** [protocol/.github#26]
`gofmt -e -d ./...` outputs the diff, which is nice, but it won't allow GitHub to annotate the PR.
It also always exits with status 0, so we'd have to look at the length of the output to actually fail the build on `gofmt` problems.

@mvdan, since you obviously spent a lot of time thinking about `gofmt`, what's the best way to run it in CI?

**Comment by mvdan** [comment]
The usual answer is `gofmt -l .`, so you get the paths that need to be formatted. Those paths can render on github PRs, I imagine, even if it temporarily requires a bit of sed.

**Comment by marten-seemann** [comment]
`gofmt -l .` just outputs the file name, not the line number / character. I don't think that's enough to (meaningfully) annotate the PR.

**Comment by mvdan** [comment]
For what reason do we want to annotate a specific line in the PR, though? For a lint tool it makes sense, since they usually point to bugs that the human should inspect and manually fix. For gofmt, the solution is to just re-run gofmt on all files.

Showing what files aren't formatted well can still be useful to avoid having to reformat all files. If GitHub does not support annotating an error for an entire file, then we could use `gofmt -l .` and annotate the first line of each result, like replacing `foo/bar.go` with `./foo/bar.go:1: need to run gofmt -w`.
