### ISSUE TITLE
Called workflows cannot be queued onto self-hosted runners ....

### ISSUE THREAD

**Issue by hsanjuan** [protocol/.github#309]
https://github.com/libp2p/go-libp2p-gorpc/actions/runs/2021789365

![image](https://user-images.githubusercontent.com/1027022/159464320-8d05ee57-e108-411f-86d7-e209a7cfff4c.png)

**Comment by galargh** [comment]
It looks like it's an ongoing GitHub issue - https://github.community/t/called-workflows-cannot-be-queued-onto-self-hosted-runners-across-organisations-enterprises-failed-to-queue-this-job-labels-ubuntu-latest/229355

**Comment by galargh** [comment]
In some cases in the past, it was an indication that there all `ubuntu-latest` machines that the organisation is allowed to use concurrently (20) were busy. 

We want to start monitoring GitHub Actions usage: https://github.com/protocol/w3dt-stewards/issues/29

Far from perfect solution to this problem is to try rerunning the workflow until it is successfully scheduled.

**Comment by galargh** [comment]
The resolution here is that we identified the problem as us running out of available runners and GitHub mislabelling the error as inability to schedule a run on a self-hosted runner.

Our long-term plan is to start monitoring activity on GitHub Actions. We're going to track this effort here: https://github.com/protocol/w3dt-stewards/issues/29

I'm going to close this issue. If you have any more reports of similar issues or you'd prefer this to stay open, please let me know.
