### ISSUE TITLE
Do "Technical Previews" make sense?

### ISSUE THREAD

**Issue by marten-seemann** [protocol/.github#367]
I see a new feature added called "Technical Previews", and I'm questioning how useful it is. If a repo opts in, it will receive all updates merged into the `next` branch, instead of `master`. I wouldn't want to enable it for any repo that I'm maintaining, as the normal web3-bot updates are already pretty noisy.

I do see the need to test updates before doing a deployment run to all repos. Maybe the following would be more useful: Repos could opt-in to _testing_ updates (without merging to master!) before we run the deployment.
Essentially, the suggestion is to have 3 branches:
1. `next`: nothing happens when a PR is merged here
1. `deploy` (feel free to suggest a better name): once this branch is moved forward, repos that opted in will receive a PR from web3-bot, but without the _automerge_ job. This would allow us to test the new version of the workflows before triggering the org-wide deployment, while also creating minimal noise.
1. `master`: this works as today. When this branch is changed, this triggers a deployment to all repos, and PRs will be automerged.

@laurentsenta @galargh wdyt?

**Comment by laurentsenta** [comment]
Having a dedicated pre-production branch with a release frequency similar to master's makes sense.

A few notes:

- We could try this now if you want: the `source_ref` config can be any branch.
- When it comes to naming, something like `develop > next > master` seems more explicit. It's easier to tell the nature and frequency of updates my project will receive.
- If technical previews are NOT auto merged, wouldn't that create more maintenance work for you? (you'd have a new PR to babysit, keep track of vulnerability fixes, etc.).

**Comment by marten-seemann** [comment]
> When it comes to naming, something like develop > next > master seems more explicit. It's easier to tell the nature and frequency of updates my project will receive.

Nice suggestion, that's a lot better!

> * If technical previews are NOT auto merged, wouldn't that create more maintenance work for you? (you'd have a new PR to babysit, keep track of vulnerability fixes, etc.).

In my mind, I don't want to have to deal with CI **at all**. I just want to be sure that it runs with the up-to-date configuration. That's why I started the Unified CI effort back then. That's why I wouldn't want to opt into Technical Previews for any of the repos (that I maintain).

I do however see that a new Unified CI configuration should be tested before a deployment to hundreds of repos is triggered. Ideally, this would be invisible to the repo maintainers. Maybe a branch would be better suited than the draft PR I suggested above. There'd probably be some tooling needed to check that the builds on that branch actually succeed. Maybe a check-list for manual checks would be good enough for the start though.

**Comment by laurentsenta** [comment]
Got it, I agree, as a user/project maintainer you should not care about the CI or we lost.
I was confused because I understand these like 2 different problems:

* **"As a project maintainer, I want to use new features before they go through the full org-wide release flow."** (like generics).
  * To me that's fixed by the technical preview feature,
  * If notifications are a problem, we should definitely introduce a pre-release branch,
  * When we release, most likely we'd opt-out projects from technical previews (since the feature they wanted is in master by then).
* **As a unified CI maintainer, I want to test new versions before we release**
  * Technical preview got us a few beta testers, but that's not enough,
  * We could do a staged rollout (add x% of the projects to the pre-release preview),
  * We could do these "shadow" releases in `preview` branches as you described,
  * Do we even need to touch your repo to try our releases? Could we have a unified-ci-sandbox repo where we pull every repo, and test the upgrade there? Maintainers don't even need to know about this.

@galargh might have a plan in mind for this

**Comment by galargh** [comment]
Sorry for getting here so late. All good points being made here.

The backstory, I added "Technical Previews" so that even though the org-wide Unified CI rollout was scheduled for 3 weeks from the Go release, one could opt-in to the new version of Unified CI ahead of schedule. This was the case for `go-libp2p` for example - https://github.com/protocol/.github/pull/369 - and we later put it back on the main release schedule - https://github.com/protocol/.github/pull/393 (note: we should have done it as part of the release but missed it; I added a comment about it in https://github.com/protocol/.github/pull/366#issuecomment-1313520645 so that we include it in the future releases). 

As such, I'd say that currently "Technical Previews" operate as an emergency feature. If there's something new in Unified CI that you cannot wait for, you can change the `source_ref`.

I like the idea of setting up `develop > next > master` flow and integrating it with a development sandbox. Unfortunately, we do not have resources to undertake such effort at the moment. Thus, I'm going to close this issue for now but I think we should definitely revisit this discussion in the future.
