### ISSUE TITLE
release checker fails on repos that don't have any previous releases

### ISSUE THREAD

**Issue by marten-seemann** [protocol/.github#381]
Example: https://github.com/marten-seemann/webtransport-go/runs/8068521958?check_suite_focus=true
<img width="762" alt="image" src="https://user-images.githubusercontent.com/1478487/187185873-8124ee5c-189d-4315-b401-7dd5c1a1ea2c.png">

**Comment by galargh** [comment]
This failed because `git tag` returned an empty response and we passed empty string as `-versions` arg value here: https://github.com/protocol/.github/blob/master/.github/workflows/release-check.yml#L55

I'll add a check for that there.

**Comment by guseggert** [comment]
I also encountered a similar failure here, not sure if it's the same root cause?  https://github.com/ipfs/boxo/actions/runs/4621371079/jobs/8172723358?pr=264

In this case we released on the `release` branch using the "release" label and in this PR we are merging `release` back into `main`. So the release already exists.

**Comment by galargh** [comment]
Yes, it's the same root cause but we might need two different fixes:
1. Release Checker should check if the tag already exists and quit if it does
2. Release Checker shouldn't fail when we're releasing a module for the very first time

**Comment by galargh** [comment]
Both of these should be satisfied by https://github.com/pl-strflt/uci/blob/651757f60e8d0df173890f1e8a4d645d4c391bf1/.github/workflows/release-check.yml now.
