### ISSUE TITLE
consider running `govulncheck` as part of go-check

### ISSUE THREAD

**Issue by marten-seemann** [protocol/.github#385]
https://go.dev/blog/vuln

**Comment by marten-seemann** [comment]
Maybe go-check is not the right place though. Vulnerabilites will be discovered independent from CI running on PRs, so this might be better suited for a cron job.

**Comment by galargh** [comment]
I could imagine us going even a step further and wanting `govulncheck` running on ALL Go repos in our orgs - not only those already signed up for Unified CI. My thinking is that `govulncheck` would serve a similar purpose to, for example, `Insights` or `Security` tab which are available on all repos. That it would be more of a repository setting rather than part of a "CI". I don't have an exact plan in mind yet but maybe we could distribute it similarly to how distribute `stale` workflow in the IPFS org - through GitHub Management.

Either way, I strongly agree that we should have it.

**Comment by galargh** [comment]
This issue was transferred to https://github.com/pl-strflt/uci/issues/43 in preparation for archiving of this repository.
