### ISSUE TITLE
Should we support opting out of 32bit tests in go-test workflow?

### ISSUE THREAD

**Issue by galargh** [protocol/.github#388]
@masih raised this in https://filecoinproject.slack.com/archives/C03KLC57LKB/p1662663509578329

**Comment by marten-seemann** [comment]
What's the motivation?

(In general, I think  it would be good to copy the relevant parts of the Slack conversation here, since Slack is getting garbage collected after a while)

**Comment by galargh** [comment]
In the Slack thread, I asked for the motivation and if using https://pkg.go.dev/cmd/go#hdr-Build_constraints might be enough to satisfy the use case. I'll update here again once we have more information.

**Comment by marten-seemann** [comment]
Pros:
* it doesn't add a lot of code complexity: the most common 32-bit build error is an const int overflow, followed by field alignments, which is super easy to fix
* if our stack is supposed to build on 32 bit machines, all of its libraries should be tested on 32 bit as well

Cons:
* it's another build job, and if the number of builders is limited, this increases build time (will be solved by using PL-hosted runners)

**Comment by masih** [comment]
@galargh @marten-seemann  many thanks for capturing an issue on this. 

The rationale is that some of the libraries used in the projects we work on unfortunately have overflow issues. These are relatively easy to fix in those library but landing the fix is out of our control in third-party code bases.

Re using build constraints it has to be applied per .go file correct? if so it makes it quite cumbersome to do. On a side node I have tried doing this [here](https://github.com/filecoin-project/go-indexer-core/blob/main/store/pebble/pebble.go#L1).  For larger packages like [this](https://github.com/filecoin-project/storetheindex/tree/main/internal) adding this per file is more of a hassle. So in that repo we ended up dropping the 32-bit build by directly modifying the workflow which of course results in periodic autogenerated PRs to revert it back.

**Comment by marten-seemann** [comment]
That makes sense to me. If the library is out of our control (and upstreaming a fix is not feasible), disabling the workflow makes sense. Adding a build constraints to _all_ .go files seems suboptimal indeed.

**Comment by masih** [comment]
This might be out of the scope; but thinking out loud I wondered if it is possible to introduce a convention in the unified CI builds to signal things like "do not run 32-bit tests". Maybe this could be a comment of sorts in the `go-test.yml` workflow? or could come from a well known file in root of the repo or in `.github` folder?

In terms of urgency, this is a nice thing to have for us; it's not too much trouble to just close off autogenerated PRs in the meantime. I understand it might take a lot of effort to make this an opt-in feature so please don't let me keep you from more important work :) Many thanks

**Comment by marten-seemann** [comment]
This could probably be solved exactly as we handle the optional `go generate` step in `go-check` (see https://github.com/protocol/.github#configuration for a description): https://github.com/protocol/.github/blob/7f2aaaeaaf9abfd5e12677d6bfd25dde41377cd6/templates/.github/workflows/go-check.yml#L20-L25

**Comment by masih** [comment]
ah excellent! that's exactly what I had in mind

**Comment by galargh** [comment]
Thanks for sharing all this info! It's going to be super helpful. I think we have all we need to proceed with this. I cannot commit us to a specific date just yet - I'd aim at landing it ahead of the next major Go version release though.

**Comment by masih** [comment]
Much obliged thank you all

**Comment by galargh** [comment]
Implemented in https://github.com/protocol/.github/pull/412
