### ISSUE TITLE
build with updated deps

### ISSUE THREAD

**Issue by marten-seemann** [protocol/.github#4]
@mvdan suggests that we could have test that update alls direct and indirect deps to their latest versions and re-build and re-tests.
That would catch bugs that occur when downstream users require a higher version of a dependency than MVS results in.

As this is expected to fail from time to time when we introduce breaking changes, a failure in this workflow should probably be treated differently from a test failure of the unit tests.

**Comment by galargh** [comment]
> As this is expected to fail from time to time when we introduce breaking changes, a failure in this workflow should probably be treated differently from a test failure of the unit tests.

We could do this kind of a build in a separate job so that it creates a separate run check. Then, as long as the repository owners don't mark the new run check as required, it wouldn't block PRs.

**Comment by mvdan** [comment]
One point worth bringing up: with the current ecosystem of libraries at PL, any project depending on ipfs or libp2p will likely fail this check most of the time, because both projects are split into dozens of v0 libraries that need to be carefully updated in sync. If, at any day, you grab all the latest releases, it's likely that there will be some build-time or run-time incompatibility at play.

Which is fine, I think. I believe we'll gradually fix that by reducing the amount of library modules we release. And this kind of sanity check will also make the breakages much more visible to our engineers. Still, I think it's worth mentioning that this will initially be mostly red.

**Comment by laurentsenta** [comment]
(triage session)
It looks like that feature would be quite noisy and the result might not be worth the effort,
Closing for now, let's re-open if/when this becomes doable.
