### ISSUE TITLE
Cache go modules and build cache

### ISSUE THREAD

**Issue by MarcoPolo** [protocol/.github#467]
Ideally this should speed up:
1. Fetching dependencies
2. Building
3. Testing (?)

**Comment by galargh** [comment]
This issue was transferred to https://github.com/pl-strflt/uci/issues/46 in preparation for archiving of this repository. FYI, it was blocked on setup-go incorrect setup of caches on Windows machine. I fixed it in https://github.com/actions/setup-go/pull/411. We'll be able to proceed with it once a release with that fix is out.
