### ISSUE TITLE
draft release notes not updated on force push

### ISSUE THREAD

**Issue by marten-seemann** [protocol/.github#480]
I was trying to cut v0.26.1 (https://github.com/libp2p/go-libp2p/pull/2146), but accidentally included too many commits in the branch. The workflow created a draft release with release notes:
<img width="904" alt="image" src="https://user-images.githubusercontent.com/1478487/221684147-349c6aae-1b0e-4edf-adc5-4e572b45af44.png">
I noticed my mistake and force-pushed the branch to only include the two fixes I intended for the release: https://github.com/libp2p/go-libp2p/pull/2146/commits

The workflows all ran, but the draft release notes were not updated. This can be annoying if you don't check and manually edit the release notes, since the new workflows would now automatically post (and GitHub would send email notifications) containing the incorrect release notes.

Note: This _might_ also happen when adding additional commits to the release branch, not only when force-pushing. I haven't tested that though.

**Comment by galargh** [comment]
> The workflows all ran, but the draft release notes were not updated. This can be annoying if you don't check and manually edit the release notes, since the new workflows would now automatically post (and GitHub would send email notifications) containing the incorrect release notes.
>
> Note: This might also happen when adding additional commits to the release branch, not only when force-pushing. I haven't tested that though.

It happens because we only generate release notes automatically the very first time a draft release is created. This is to preserve any potential manual updates to the notes that users might have introduced after the draft was initially created. 

As part of the resolution of this issue we should figure out if we can get a clear information on whether the notes where modified after creation. One idea I have is to add a comment to the automatically generated notes - something along the lines of `remove me if you don't want future pushes to overwrite your changes`. Then we could check if the comment exists and act accordingly.

I'm going to close this issue as I'm preparing to archive this repo but I'm going to continue tracking it under https://github.com/pl-strflt/uci/issues/48.
