### ISSUE TITLE
Can't deploy PRs merged from forks

### ISSUE THREAD

**Issue by Stebalien** [protocol/.github#49]
https://github.com/protocol/.github/actions/runs/712309930

**Comment by marten-seemann** [comment]
This is weird. This *should* work. Will investigate.

**Comment by marten-seemann** [comment]
The problem is that we run `dispatch` on `pull_request`:
https://github.com/protocol/.github/blob/5560e9602a114661f7d9c761ee2604f6e00f38a8/.github/workflows/dispatch.yml#L5-L8

PRs don't have access to repository secrets (which makes sense), but apparently this also applies to merged PRs (which makes less sense).
